spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elk-city?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&userSSL=false
    initialization-mode:  always
    username: root
    password: vae1986@mysql