spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elk-city?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&userSSL=false
    initialization-mode: never
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/elk-city?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&userSSL=false
      username: root
      password: vae1986@mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
  thymeleaf:
    cache: false
    mode: HTML
server:
  #chrome浏览器限制部分端口
  port: 8081
logging:
  level:
    club.p9j7: INFO
    us.codecraft.webmagic: INFO
    org.springframework.data.elasticsearch: INFO